import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import 'bootstrap/dist/css/bootstrap.min.css';
import './style.css';

const API = import.meta.env.VITE_API_URL || 'http://api.reihakushiranui.bond';
async function request(path, options = {}) { const r = await fetch(API + path, { credentials: 'include', ...options }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.error || data.message || `Request failed (${r.status})`); return data; }
const get = path => request(path + (path.includes('?')?'&':'?') + '_ts=' + Date.now());
const post = (path, body) => request(path, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body) });
const patch = (path, body) => request(path, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body) });
const del = path => request(path, { method:'DELETE' });
function formatPlaytime(seconds=0){const h=Math.floor(seconds/3600);const m=Math.floor((seconds%3600)/60);return `${h}j ${m}m`;}
function initials(name='SM'){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'SM';}

function App(){
 const [me,setMe]=useState(null),[settings,setSettings]=useState(null),[members,setMembers]=useState([]),[live,setLive]=useState([]),[att,setAtt]=useState([]),[server,setServer]=useState(null),[detected,setDetected]=useState([]);
 const [search,setSearch]=useState(''),[section,setSection]=useState('overview'),[msg,setMsg]=useState(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false);
 const [memberModal,setMemberModal]=useState(null);
 const [settingsForm,setSettingsForm]=useState(null),[savingSettings,setSavingSettings]=useState(false),[testingCfx,setTestingCfx]=useState(false),[settingsDirty,setSettingsDirty]=useState(false);
 const load=async(silent=false)=>{if(!silent)setRefreshing(true);try{const m=await get('/api/me');setMe({...((m&&m.user)||{}),authenticated:!!m.authenticated});if(m.authenticated){const [s,md,l,a,sv,dt]=await Promise.all([get('/api/settings'),get('/api/members'),get('/api/live'),get('/api/attendance'),get('/api/server').catch(()=>null),get('/api/detected').catch(()=>({players:[]}))]);setSettings({...s,serverLogoUrl:s.serverLogoUrl||m?.settings?.serverLogoUrl||''});if(!settingsDirty||!settingsForm){setSettingsForm({...s,factionTags:(s.factionTags||[]).join(', ')});setSettingsDirty(false);}setMembers(md||[]);setLive(l||[]);setAtt(a||[]);setServer(sv);setDetected(dt?.players||[]);}}catch(e){console.error(e);setMsg({type:'danger',text:e.message});}finally{setLoading(false);setRefreshing(false);}};
 useEffect(()=>{load();const t=setInterval(()=>load(true),10000);return()=>clearInterval(t);},[]);
 const onlineIds=useMemo(()=>new Set(live.map(x=>String(x.memberId||x.member?._id||x.id))),[live]);
 const onlineMembers=useMemo(()=>members.filter(m=>onlineIds.has(String(m._id))),[members,onlineIds]);
 const attendedCount=att.filter(x=>x.status==='attended').length;
 const filteredMembers=members.filter(m=>`${m.nickIC||''} ${m.nickFiveM||''} ${m.steamHex||''} ${m.discordId||''}`.toLowerCase().includes(search.toLowerCase()));
 const markSetting=(k,v)=>{setSettingsDirty(true);setSettingsForm(x=>({...x,[k]:v}));};
 const saveSettings=async e=>{e?.preventDefault?.();if(savingSettings||!settingsForm)return;setSavingSettings(true);setMsg(null);try{const d={...settingsForm,factionTags:String(settingsForm.factionTags).split(',').map(x=>x.trim()).filter(Boolean),pollIntervalSeconds:Number(settingsForm.pollIntervalSeconds),minimumPlaytimeMinutes:Number(settingsForm.minimumPlaytimeMinutes)};const saved=await patch('/api/settings',d);setSettings(saved);setSettingsForm({...saved,factionTags:(saved.factionTags||[]).join(', ')});setSettingsDirty(false);setMsg({type:'success',text:'Settings tersimpan. CFX polling dan Discord bot akan memakai konfigurasi terbaru.'});await load(true);}catch(e){setMsg({type:'danger',text:e.message});}finally{setSavingSettings(false);}};
 const testCfx=async()=>{setTestingCfx(true);setMsg(null);try{const x=await post('/api/settings/test-cfx',{});setMsg({type:'success',text:`CFX OK — ${x.serverName||settings?.cfxServerName} • ${x.playerCount||0} player terdeteksi.`});}catch(e){setMsg({type:'danger',text:`CFX test gagal: ${e.message}`});}finally{setTestingCfx(false);}};
 const logout=async()=>{try{await post('/auth/logout',{});location.reload();}catch(e){setMsg({type:'danger',text:e.message});}};
 if(loading)return <LoadingScreen name={settings?.appName||'Satu Mimpi'}/>;
 if(!me?.authenticated)return <Login settings={me?.settings||{}}/>;
 return <div className="shell">
  <aside className="sidebar"><div className="brand"><div className="brand-logo server-logo-box">{settings?.serverLogoUrl?<img src={settings.serverLogoUrl} alt="Server logo"/>:initials(settings?.appName)}</div><div><div className="brand-name">{settings?.appName||'Satu Mimpi'}</div><div className="brand-caption">{settings?.factionName||'H2'} • ADMIN</div></div></div>
   <div className="sidebar-label">Workspace</div><NavItem active={section==='overview'} icon="⌂" label="Overview" onClick={()=>setSection('overview')}/><NavItem active={section==='detected'} icon="◈" label="Auto Detected" count={detected.length} onClick={()=>setSection('detected')}/><NavItem active={section==='members'} icon="♙" label="Members" count={members.length} onClick={()=>setSection('members')}/><NavItem active={section==='attendance'} icon="✓" label="Attendance" onClick={()=>setSection('attendance')}/>
   <div className="sidebar-label mt-4">System</div><NavItem active={section==='settings'} icon="⚙" label="Settings" onClick={()=>setSection('settings')}/>
   <div className="server-mini"><span className="pulse"/><div><strong>{settings?.cfxServerName||'CFX Server'}</strong><small>{server?.clients ?? live.length} players online</small></div></div>
   <div className="sidebar-footer"><div className="discord-avatar-wrap">{me.avatarUrl?<img className="discord-avatar" src={me.avatarUrl} alt="Discord profile"/>:<div className="admin-avatar">{initials(me.globalName||me.username||'Admin')}</div>}</div><div className="flex-grow-1 discord-profile"><strong>{me.displayName||me.globalName||me.username||'Discord User'}</strong><small>@{me.username||'discord'}</small></div><button className="logout-btn" onClick={logout} title="Logout">↪</button></div>
  </aside>
  <main className="content"><header className="topbar"><div className="mobile-brand"><div className="brand-logo sm server-logo-box">{settings?.serverLogoUrl?<img src={settings.serverLogoUrl} alt="Server logo"/>:initials(settings?.appName)}</div><strong>{settings?.appName||'Satu Mimpi'}</strong></div><div className="topbar-right"><div className="live-indicator"><span className="pulse"/> SYSTEM LIVE</div><button className="icon-btn" onClick={()=>load()} title="Refresh">↻</button><span className="refresh-text">{refreshing?'Updating…':'Auto refresh 10s'}</span></div></header>
   <div className="page-wrap">{msg&&<div className={`alert premium-alert alert-${msg.type} alert-dismissible fade show`}><span>{msg.type==='success'?'✓':'!'}</span>{msg.text}<button type="button" className="btn-close" onClick={()=>setMsg(null)}/></div>}
    {section==='overview'&&<Overview appName={settings?.appName} factionName={settings?.factionName} serverName={settings?.cfxServerName} adminName={me.displayName||me.globalName||me.username} members={members} onlineMembers={onlineMembers} att={att} live={live} onAdd={()=>setMemberModal({mode:'add'})} onMembers={()=>setSection('members')}/>} 
    {section==='detected'&&<DetectedPlayers players={detected} onAdd={p=>setMemberModal({mode:'add',member:{nickFiveM:p.name,nickIC:p.name,steamHex:p.steamHex||'',discordId:p.discordId||'',cfxId:p.cfxId||''}})}/>}
    {section==='members'&&<Members members={filteredMembers} onlineIds={onlineIds} search={search} setSearch={setSearch} onAdd={()=>setMemberModal({mode:'add'})} onEdit={m=>setMemberModal({mode:'edit',member:m})} onDelete={async m=>{if(!confirm(`Hapus member ${m.nickIC||m.nickFiveM||m.steamHex}?`))return;try{await del(`/api/members/${m._id}`);setMsg({type:'success',text:'Member berhasil dihapus.'});await load(true);}catch(e){setMsg({type:'danger',text:e.message});}}}/>} 
    {section==='attendance'&&<Attendance att={att} settings={settings}/>} 
    {section==='settings'&&settingsForm&&<SettingsPage form={settingsForm} setForm={setSettingsForm} onFieldChange={markSetting} onSave={saveSettings} saving={savingSettings} onTestCfx={testCfx} testingCfx={testingCfx}/>} 
   </div>
  </main>
  {memberModal&&<MemberModal mode={memberModal.mode} member={memberModal.member} factionName={settings?.factionName} onClose={()=>setMemberModal(null)} onSaved={async()=>{setMemberModal(null);setMsg({type:'success',text:'Member berhasil disimpan.'});await load(true);}} onError={e=>setMsg({type:'danger',text:e.message})}/>} 
 </div>;
}
function LoadingScreen({name}){return <div className="loading-screen"><div className="loader-logo">{initials(name)}</div><div className="spinner-border text-warning mt-4"/><p>Memuat {name} Dashboard…</p></div>}
function Login({settings}){const name=settings?.appName||'Configuration';const subtitle=settings?.appSubtitle||'Faction attendance & member monitoring.';const eyebrow=settings?.loginEyebrow||'ADMIN CONTROL CENTER';const button=settings?.loginButtonText||'Continue with Discord';const footer=settings?.loginFooterText||'Restricted to authorized administrators';return <div className="login-screen"><div className="login-glow"/><div className="login-card"><div className="brand-logo lg login-server-logo">{settings?.serverLogoUrl?<img src={settings.serverLogoUrl} alt="Server logo"/>:initials(name)}</div><div className="eyebrow">{eyebrow}</div><h1>{name}</h1><p>{subtitle}</p><a className="login-btn" href={`${API}/auth/discord`}><span>◈</span> {button}</a><small>{footer}</small></div></div>}
function NavItem({active,icon,label,count,onClick}){return <button className={`nav-item ${active?'active':''}`} onClick={onClick}><span className="nav-icon">{icon}</span><span>{label}</span>{count!=null&&<em>{count}</em>}</button>}
function Overview({appName,factionName,serverName,adminName,members,onlineMembers,att,live,onAdd,onMembers}){const attended=att.filter(x=>x.status==='attended').length;return <><div className="hero-row"><div><div className="eyebrow">{factionName||'FACTION'} ATTENDANCE</div><h1>Good evening, {adminName||'Admin'}.</h1><p>Monitor member activity across {serverName||appName||'your server'}.</p></div><button className="gold-btn" onClick={onAdd}>＋ Register Member</button></div><div className="stats-grid"><Stat title="Total Members" value={members.length} meta="Registered members" icon="♙"/><Stat title="Online Now" value={onlineMembers.length} meta="Currently in server" icon="●" green/><Stat title="Attendance" value={attended} meta="Meeting minimum playtime" icon="✓"/><Stat title="Offline" value={Math.max(members.length-onlineMembers.length,0)} meta="Not currently online" icon="○" muted/></div><div className="section-grid"><section className="panel panel-main"><PanelHead title="Live Members" subtitle={`${live.length} player(s) detected`} action="View all" onClick={onMembers}/><div className="member-list">{live.length?live.slice(0,7).map((p,i)=><LiveRow key={p.id||i} p={p}/>):<Empty text="Tidak ada member yang sedang online."/>}</div></section><section className="panel"><PanelHead title="Attendance" subtitle="Today's recap"/><div className="attendance-summary"><div className="donut"><div><strong>{members.length?Math.round((attended/members.length)*100):0}%</strong><span>attended</span></div></div><div className="legend"><Legend label="Hadir" value={attended} cls="gold"/><Legend label="Belum hadir" value={Math.max(members.length-attended,0)} cls="muted"/></div></div></section></div><section className="panel"><PanelHead title="Member Directory" subtitle="Recently registered members" action="Manage members" onClick={onMembers}/><div className="table-wrap"><MemberTable members={members.slice(0,6)} onlineIds={new Set(onlineMembers.map(m=>String(m._id)))}/></div></section></>}
function Stat({title,value,meta,icon,green,muted}){return <div className="stat"><div className={`stat-symbol ${green?'green':muted?'muted':''}`}>{icon}</div><div className="stat-copy"><span>{title}</span><strong>{value}</strong><small>{meta}</small></div></div>}
function PanelHead({title,subtitle,action,onClick}){return <div className="panel-head"><div><h2>{title}</h2><p>{subtitle}</p></div>{action&&<button onClick={onClick}>{action} <span>→</span></button>}</div>}
function LiveRow({p}){const m=p.member||{};return <div className="live-row"><div className="avatar">{initials(m.nickIC||p.name)}</div><div className="live-info"><strong>{m.nickIC||p.name||'Unknown'}</strong><span>{p.name||m.nickFiveM||'FiveM player'} • {p.matchedBy||'detected'}</span></div><div className="live-status"><span className="pulse"/> Online</div></div>}
function Legend({label,value,cls}){return <div><span className={`dot ${cls}`}/><span>{label}</span><strong>{value}</strong></div>}
function Empty({text}){return <div className="empty">{text}</div>}
function Members({members,onlineIds,search,setSearch,onAdd,onEdit,onDelete}){return <><div className="hero-row compact"><div><div className="eyebrow">MEMBER MANAGEMENT</div><h1>Members</h1><p>Edit, remove, or register faction members.</p></div><button className="gold-btn" onClick={onAdd}>＋ Register Member</button></div><section className="panel"><div className="toolbar"><div className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search member, FiveM name, Steam Hex…"/></div><span className="result-count">{members.length} members</span></div><div className="table-wrap"><MemberTable members={members} onlineIds={onlineIds} full onEdit={onEdit} onDelete={onDelete}/></div></section></>}
function MemberTable({members,onlineIds,full,onEdit,onDelete}){return <table className="premium-table"><thead><tr><th>Member</th><th>Nick FiveM</th><th>Discord ID</th><th>Steam Hex</th><th>Status</th>{full&&<th>Actions</th>}</tr></thead><tbody>{members.length?members.map(m=>{const online=onlineIds.has(String(m._id));return <tr key={m._id}><td><div className="table-member"><div className="avatar">{initials(m.nickIC||m.nickFiveM)}</div><div><strong>{m.nickIC||'Belum terdeteksi'}</strong><small>Faction {m.faction||'-'}</small></div></div></td><td>{m.nickFiveM||<span className="dim">Belum terdeteksi</span>}</td><td className="mono">{m.discordId||'—'}</td><td className="mono steam-cell">{m.steamHex||'—'}</td><td><Status online={online}/></td>{full&&<td><div className="table-actions"><button className="mini-btn" onClick={()=>onEdit(m)}>Edit</button><button className="mini-btn danger" onClick={()=>onDelete(m)}>Remove</button></div></td>}</tr>}) : <tr><td colSpan={full?6:5}><Empty text="Belum ada member terdaftar."/></td></tr>}</tbody></table>}
function Status({online}){return <span className={`status ${online?'online':'offline'}`}><i/> {online?'Online':'Offline'}</span>}
function Attendance({att,settings}){const start=settings?.shiftStartTime||'21:00';const end=settings?.shiftEndTime||'01:00';const tz=settings?.timezone||'Asia/Jakarta';const shift=settings?.shiftName||'Wajib Shift';return <><div className="hero-row compact"><div><div className="eyebrow">DAILY RECAP</div><h1>Attendance</h1><p>Wajib online <strong>{start} — {end}</strong> ({tz}). Shift: <strong>{shift}</strong>. Rekap berdasarkan minimum playtime.</p></div><div className="date-chip">Today</div></div><section className="panel"><PanelHead title="Today's Attendance" subtitle={`${att.length} record(s)`}/><div className="table-wrap"><table className="premium-table"><thead><tr><th>Status</th><th>Member</th><th>Nick FiveM</th><th>Playtime</th></tr></thead><tbody>{att.length?att.map(x=><tr key={x._id}><td><span className={`attendance-badge ${x.status==='attended'?'yes':'no'}`}>{x.status==='attended'?'✓ Hadir':'× Tidak Hadir'}</span></td><td><strong>{x.nickIC||'Unknown'}</strong></td><td>{x.nickFiveM||'—'}</td><td className="mono">{formatPlaytime(x.totalSeconds)}</td></tr>):<tr><td colSpan="4"><Empty text="Belum ada data attendance."/></td></tr>}</tbody></table></div></section></>}

function DetectedPlayers({players,onAdd}){return <><div className="hero-row compact"><div><div className="eyebrow">AUTOMATIC CFX DATA</div><h1>Auto Detected</h1><p>Player yang terdeteksi dari server dan memenuhi faction tag. Data ini tidak membuat member secara otomatis.</p></div></div><section className="panel"><PanelHead title="Detected Players" subtitle={`${players.length} player(s) terdeteksi`}/><div className="table-wrap"><table className="premium-table"><thead><tr><th>Player</th><th>Steam Hex</th><th>CFX ID</th><th>Discord ID</th><th>Status</th><th>Action</th></tr></thead><tbody>{players.length?players.map((p,i)=><tr key={`${p.id}-${i}`}><td><strong>{p.name}</strong><div className="table-sub">Ping: {p.ping??'—'}</div></td><td className="mono">{p.steamHex||'—'}</td><td className="mono">{p.cfxId||'—'}</td><td className="mono">{p.discordId||'—'}</td><td>{p.member?<span className="attendance-badge yes">✓ Registered</span>:<span className="attendance-badge no">Detected</span>}</td><td>{p.member?<span className="setting-help">Already in Members</span>:<button className="gold-btn small" onClick={()=>onAdd(p)}>＋ Add</button>}</td></tr>):<tr><td colSpan="6"><Empty text="Tidak ada player faction yang sedang terdeteksi."/></td></tr>}</tbody></table></div></section></>}
function TagEditor({value,onChange}){const tags=String(value||'').split(',').map(x=>x.trim()).filter(Boolean);const [input,setInput]=useState('');const add=()=>{const v=input.trim();if(!v)return;if(!tags.some(x=>x.toLowerCase()===v.toLowerCase()))onChange([...tags,v].join(', '));setInput('');};const remove=t=>onChange(tags.filter(x=>x.toLowerCase()!==t.toLowerCase()).join(', '));return <div className="tag-editor"><span className="field-label">Faction Auto-Detect Tags</span><div className="tag-list">{tags.map(t=><span className="config-tag" key={t}>{t}<button type="button" onClick={()=>remove(t)}>×</button></span>)}</div><div className="tag-add-row"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add();}}} placeholder="Contoh: H2"/><button type="button" className="ghost-btn" onClick={add}>＋ Add Tag</button></div></div>}
function SettingsPage({form,setForm,onFieldChange,onSave,saving,onTestCfx,testingCfx}){const set=(k,v)=>onFieldChange?onFieldChange(k,v):setForm(x=>({...x,[k]:v}));const submitOnEnter=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&!e.defaultPrevented){const el=e.target;if(el instanceof HTMLTextAreaElement)return;e.preventDefault();if(!saving)onSave(e);}};return <>
 <div className="settings-header"><div><div className="eyebrow">SYSTEM CONFIGURATION</div><h1>Settings</h1><p>Kelola identitas aplikasi, auto-detect faction, server CFX, shift wajib, dan integrasi Discord dari satu halaman.</p></div><button className="gold-btn settings-save" onClick={onSave} disabled={saving}>{saving?'Saving…':'Save Settings'}</button></div>
 <form onSubmit={onSave} onKeyDownCapture={submitOnEnter} className="settings-grid">
  <section className="panel settings-panel"><PanelHead title="Branding" subtitle="Identitas utama yang tampil di dashboard dan bot."/><div className="settings-body"><div className="settings-section-icon">✦</div><Field label="Application / Server Name" value={form.appName} onChange={v=>set('appName',v)} placeholder="Satu Mimpi"/><Field label="Subtitle" value={form.appSubtitle} onChange={v=>set('appSubtitle',v)} placeholder="Faction attendance & member monitoring."/><Field label="Server Logo URL" value={form.serverLogoUrl||''} onChange={v=>set('serverLogoUrl',v)} placeholder="https://.../logo.png"/><div className="setting-help">Logo ini dipakai di sidebar dan login page. Jika kosong, sistem mencoba memakai icon Discord Server.</div></div></section>
  <section className="panel settings-panel"><PanelHead title="Login Page" subtitle="Semua teks dan tampilan halaman login."/><div className="settings-body"><Field label="Login Eyebrow" value={form.loginEyebrow} onChange={v=>set('loginEyebrow',v)} placeholder="ADMIN CONTROL CENTER"/><Field label="Login Button Text" value={form.loginButtonText} onChange={v=>set('loginButtonText',v)} placeholder="Continue with Discord"/><Field label="Login Footer Text" value={form.loginFooterText} onChange={v=>set('loginFooterText',v)} placeholder="Restricted to authorized administrators"/><div className="setting-help">Judul login mengikuti <strong>Application / Server Name</strong> dan deskripsi mengikuti <strong>Subtitle</strong>.</div></div></section>
  <section className="panel settings-panel"><PanelHead title="Faction Auto-Detect" subtitle="Tentukan inisial/tag yang boleh muncul di Auto Detected."/><div className="settings-body"><Field label="Faction Name" value={form.factionName} onChange={v=>set('factionName',v)} placeholder="H2"/><TagEditor value={form.factionTags||''} onChange={v=>set('factionTags',v)}/><div className="setting-help">Contoh <code>H2</code> akan mendeteksi <code>H2 - Reihaku</code>, <code>Reihaku #H2</code>, dan <code>SGXH2 Law</code>. Player hanya masuk <strong>Auto Detected</strong>, bukan Members, sampai admin menekan <strong>Add</strong>.</div></div></section>
  <section className="panel settings-panel"><PanelHead title="CFX / FiveM Server" subtitle="Server yang dipantau oleh sistem."/><div className="settings-body"><div className="field-row-2"><Field label="CFX Server ID" value={form.cfxServerId} onChange={v=>set('cfxServerId',v)} placeholder="6gk4e4"/><Field label="Server Display Name" value={form.cfxServerName} onChange={v=>set('cfxServerName',v)} placeholder="Satu Mimpi Roleplay"/></div><Field label="CFX API Base" value={form.cfxApiBase} onChange={v=>set('cfxApiBase',v)} placeholder="https://frontend.cfx-services.net/api/servers/single"/><div className="field-row-2"><Field label="Poll Interval (seconds)" type="number" value={form.pollIntervalSeconds} onChange={v=>set('pollIntervalSeconds',v)} min="10"/><Field label="Timezone" value={form.timezone} onChange={v=>set('timezone',v)} placeholder="Asia/Jakarta"/></div><div className="settings-actions"><button type="button" className="ghost-btn" onClick={onTestCfx} disabled={testingCfx}>{testingCfx?'Testing…':'Test CFX Connection'}</button></div></div></section>
  <section className="panel settings-panel"><PanelHead title="Wajib Shift" subtitle="Jam absensi yang berlaku untuk semua member."/><div className="settings-body"><Field label="Shift Name" value={form.shiftName} onChange={v=>set('shiftName',v)} placeholder="Wajib Shift"/><div className="field-row-2"><Field label="Start Time" type="time" value={form.shiftStartTime||'21:00'} onChange={v=>set('shiftStartTime',v)}/><Field label="End Time" type="time" value={form.shiftEndTime||'01:00'} onChange={v=>set('shiftEndTime',v)}/></div><div className="field-row-2"><Field label="Minimum Playtime (minutes)" type="number" value={form.minimumPlaytimeMinutes} onChange={v=>set('minimumPlaytimeMinutes',v)} min="1"/><Field label="Timezone" value={form.timezone||'Asia/Jakarta'} onChange={v=>set('timezone',v)} placeholder="Asia/Jakarta"/></div><div className="shift-fixed-card"><strong>{form.shiftStartTime||'21:00'} — {form.shiftEndTime||'01:00'}</strong><span>{form.shiftName||'Wajib Shift'} • {form.timezone||'Asia/Jakarta'} • minimum {form.minimumPlaytimeMinutes||120} menit</span></div><div className="setting-help">Jika End Time lebih kecil dari Start Time, sistem otomatis menganggapnya <strong>overnight</strong>.</div></div></section>
  <section className="panel settings-panel settings-wide"><PanelHead title="Discord Bot Integration" subtitle="Konfigurasi website dan bot tetap sinkron dari settings ini."/><div className="settings-body"><div className="field-row-2"><Field label="Discord Guild / Server ID" value={form.discordGuildId} onChange={v=>set('discordGuildId',v)} placeholder="1234567890"/><Field label="Admin Role ID" value={form.discordAdminRoleId} onChange={v=>set('discordAdminRoleId',v)} placeholder="1234567890"/></div><div className="field-row-2"><Field label="Player Log Channel ID" value={form.discordPlayerLogChannelId||''} onChange={v=>set('discordPlayerLogChannelId',v)} placeholder="Online + Offline"/><Field label="Attendance Channel ID" value={form.discordAttendanceChannelId||''} onChange={v=>set('discordAttendanceChannelId',v)} placeholder="Attendance / Recap"/></div><div className="setting-help">🟢 Online dan 🔴 Offline masuk ke <strong>Player Log Channel</strong>. 📋 Attendance/recap masuk ke <strong>Attendance Channel</strong>.</div><div className="setting-help">Token Discord dan OAuth secret tetap berada di <code>.env</code>. Field di sini hanya mengatur server, role, channel, dan tampilan integrasi.</div></div></section>
  <div className="settings-bottom-save"><span>Perubahan berlaku setelah disimpan.</span><button className="gold-btn" type="submit" disabled={saving}>{saving?'Saving…':'Save Settings'}</button></div>
 </form></>}
function Field({label,value,onChange,type='text',placeholder='',min}){return <label className="setting-field"><span>{label}</span><input type={type} value={value??''} min={min} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function MemberModal({mode,member,factionName,onClose,onSaved,onError}){const [form,setForm]=useState({steamHex:member?.steamHex||'',nickFiveM:member?.nickFiveM||'',nickIC:member?.nickIC||'',discordId:member?.discordId||'',cfxId:member?.cfxId||''});const [saving,setSaving]=useState(false);const save=async e=>{e.preventDefault();setSaving(true);try{if(mode==='add')await post('/api/members',form);else await patch(`/api/members/${member._id}`,form);await onSaved();}catch(err){onError(err);}finally{setSaving(false);}};return <div className="modal-backdrop-custom" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="add-modal member-modal"><button className="modal-close" onClick={onClose}>×</button><div className="modal-icon">{mode==='add'?'⌁':'✎'}</div><div className="eyebrow">{mode==='add'?'NEW MEMBER':'EDIT MEMBER'}</div><h2>{mode==='add'?'Register Member':'Edit Member'}</h2><p>Steam Hex bersifat <strong>optional</strong>. Jika tersedia, sistem memakainya sebagai identity utama. Jika kosong, Nick FiveM/Nick IC dapat digunakan untuk pencocokan player.</p><form onSubmit={save}><div className="inline-fields"><Field label="Nick IC" value={form.nickIC} onChange={v=>setForm(x=>({...x,nickIC:v}))} placeholder="Nama IC"/><Field label="Nick FiveM" value={form.nickFiveM} onChange={v=>setForm(x=>({...x,nickFiveM:v}))} placeholder="Nama FiveM"/></div><Field label="Steam Hex (Optional)" value={form.steamHex} onChange={v=>setForm(x=>({...x,steamHex:v}))} placeholder="Boleh dikosongkan • steam:1100001xxxxxxxx"/><div className="inline-fields"><Field label="Discord ID" value={form.discordId} onChange={v=>setForm(x=>({...x,discordId:v}))} placeholder="Optional"/><Field label="CFX/FiveM ID" value={form.cfxId} onChange={v=>setForm(x=>({...x,cfxId:v}))} placeholder="Optional"/></div><div className="setting-help">Faction saat ini: <strong>{factionName||'H2'}</strong>. Nick IC/FiveM juga dapat diperbarui otomatis ketika player terdeteksi online.</div><div className="modal-actions"><button type="button" className="ghost-btn" onClick={onClose}>Cancel</button><button className="gold-btn" type="submit" disabled={saving}>{saving?'Saving…':mode==='add'?'Register Member':'Save Changes'}</button></div></form></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
